name: Release Candidate

on:
  pull_request:
    types: [ closed ]
    branches:
      - develop

jobs:
  release_on_merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine RC version
        id: rc_version
        run: |
          # Get the latest non-RC tag
          BASE_VERSION=$(git describe --tags --abbrev=0 --match "[0-9]*.[0-9]*.[0-9]*" 2>/dev/null || echo "0.0.0")
          # Count the number of RCs for this version
          RC_COUNT=$(git tag -l "${BASE_VERSION}-rc.*" | wc -l)
          RC_NUMBER=$((RC_COUNT + 1))
          RC_VERSION="${BASE_VERSION}-rc.${RC_NUMBER}"
          echo "RC_VERSION=${RC_VERSION}" >> $GITHUB_OUTPUT

      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: none
          tag_name: ${{ steps.rc_version.outputs.RC_VERSION }}
          tag_prefix: ""
          release_name: "Release Candidate ${{ steps.rc_version.outputs.RC_VERSION }}"

    outputs:
      version: ${{ steps.release.outputs.version }}
